/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as ApiAgentRunsRouteImport } from './routes/api.agent-runs'
import { Route as ApiAgentStatusRouteImport } from './routes/api/agent-status'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiWorkspaceRouteImport } from './routes/api.workspace'
import { Route as ApiDecisionsEditorialRouteImport } from './routes/api.decisions.editorial'
import { Route as ApiDeliveryCompileRouteImport } from './routes/api.delivery.compile'
import { Route as ApiGraphNodesRouteImport } from './routes/api.graph.nodes'
import { Route as ApiProvenanceDeliveryIdRouteImport } from './routes/api.provenance.$deliveryId'
import { Route as ApiRuntimeProposalsRouteImport } from './routes/api.runtime.proposals'
import { Route as ApiScriptGitApplyRouteImport } from './routes/api.script-git.apply'
import { Route as ApiScriptGitLoadRouteImport } from './routes/api.script-git.load'
import { Route as ApiScriptGitRevertRouteImport } from './routes/api.script-git.revert'
import { Route as ApiTestResetRouteImport } from './routes/api.test.reset'
import { Route as ApiAgentRunsRunIdEventsRouteImport } from './routes/api.agent-runs.$runId.events'
import { Route as ApiDeliveryVariantIdApproveRouteImport } from './routes/api.delivery.$variantId.approve'
import { Route as ApiDeliveryVariantIdResolveRouteImport } from './routes/api.delivery.$variantId.resolve'
import { Route as ApiGraphNodesNodeIdRouteImport } from './routes/api.graph.nodes.$nodeId'
import { Route as ApiNodesNodeIdImpactRouteImport } from './routes/api.nodes.$nodeId.impact'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRunsRoute = ApiAgentRunsRouteImport.update({
  id: '/api/agent-runs',
  path: '/api/agent-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStatusRoute = ApiAgentStatusRouteImport.update({
  id: '/api/agent-status',
  path: '/api/agent-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDecisionsEditorialRoute = ApiDecisionsEditorialRouteImport.update({
  id: '/api/decisions/editorial',
  path: '/api/decisions/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeliveryCompileRoute = ApiDeliveryCompileRouteImport.update({
  id: '/api/delivery/compile',
  path: '/api/delivery/compile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphNodesRoute = ApiGraphNodesRouteImport.update({
  id: '/api/graph/nodes',
  path: '/api/graph/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvenanceDeliveryIdRoute = ApiProvenanceDeliveryIdRouteImport.update({
  id: '/api/provenance/$deliveryId',
  path: '/api/provenance/$deliveryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeProposalsRoute = ApiRuntimeProposalsRouteImport.update({
  id: '/api/runtime/proposals',
  path: '/api/runtime/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScriptGitApplyRoute = ApiScriptGitApplyRouteImport.update({
  id: '/api/script-git/apply',
  path: '/api/script-git/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScriptGitLoadRoute = ApiScriptGitLoadRouteImport.update({
  id: '/api/script-git/load',
  path: '/api/script-git/load',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScriptGitRevertRoute = ApiScriptGitRevertRouteImport.update({
  id: '/api/script-git/revert',
  path: '/api/script-git/revert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestResetRoute = ApiTestResetRouteImport.update({
  id: '/api/test/reset',
  path: '/api/test/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRunsRunIdEventsRoute = ApiAgentRunsRunIdEventsRouteImport.update({
  id: '/$runId/events',
  path: '/$runId/events',
  getParentRoute: () => ApiAgentRunsRoute,
} as any)
const ApiDeliveryVariantIdApproveRoute =
  ApiDeliveryVariantIdApproveRouteImport.update({
    id: '/api/delivery/$variantId/approve',
    path: '/api/delivery/$variantId/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDeliveryVariantIdResolveRoute =
  ApiDeliveryVariantIdResolveRouteImport.update({
    id: '/api/delivery/$variantId/resolve',
    path: '/api/delivery/$variantId/resolve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGraphNodesNodeIdRoute = ApiGraphNodesNodeIdRouteImport.update({
  id: '/$nodeId',
  path: '/$nodeId',
  getParentRoute: () => ApiGraphNodesRoute,
} as any)
const ApiNodesNodeIdImpactRoute = ApiNodesNodeIdImpactRouteImport.update({
  id: '/api/nodes/$nodeId/impact',
  path: '/api/nodes/$nodeId/impact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRoute
  '/api/agent-runs': typeof ApiAgentRunsRouteWithChildren
  '/api/agent-status': typeof ApiAgentStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/decisions/editorial': typeof ApiDecisionsEditorialRoute
  '/api/delivery/compile': typeof ApiDeliveryCompileRoute
  '/api/graph/nodes': typeof ApiGraphNodesRouteWithChildren
  '/api/provenance/$deliveryId': typeof ApiProvenanceDeliveryIdRoute
  '/api/runtime/proposals': typeof ApiRuntimeProposalsRoute
  '/api/script-git/apply': typeof ApiScriptGitApplyRoute
  '/api/script-git/load': typeof ApiScriptGitLoadRoute
  '/api/script-git/revert': typeof ApiScriptGitRevertRoute
  '/api/test/reset': typeof ApiTestResetRoute
  '/api/agent-runs/$runId/events': typeof ApiAgentRunsRunIdEventsRoute
  '/api/delivery/$variantId/approve': typeof ApiDeliveryVariantIdApproveRoute
  '/api/delivery/$variantId/resolve': typeof ApiDeliveryVariantIdResolveRoute
  '/api/graph/nodes/$nodeId': typeof ApiGraphNodesNodeIdRoute
  '/api/nodes/$nodeId/impact': typeof ApiNodesNodeIdImpactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRoute
  '/api/agent-runs': typeof ApiAgentRunsRouteWithChildren
  '/api/agent-status': typeof ApiAgentStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/decisions/editorial': typeof ApiDecisionsEditorialRoute
  '/api/delivery/compile': typeof ApiDeliveryCompileRoute
  '/api/graph/nodes': typeof ApiGraphNodesRouteWithChildren
  '/api/provenance/$deliveryId': typeof ApiProvenanceDeliveryIdRoute
  '/api/runtime/proposals': typeof ApiRuntimeProposalsRoute
  '/api/script-git/apply': typeof ApiScriptGitApplyRoute
  '/api/script-git/load': typeof ApiScriptGitLoadRoute
  '/api/script-git/revert': typeof ApiScriptGitRevertRoute
  '/api/test/reset': typeof ApiTestResetRoute
  '/api/agent-runs/$runId/events': typeof ApiAgentRunsRunIdEventsRoute
  '/api/delivery/$variantId/approve': typeof ApiDeliveryVariantIdApproveRoute
  '/api/delivery/$variantId/resolve': typeof ApiDeliveryVariantIdResolveRoute
  '/api/graph/nodes/$nodeId': typeof ApiGraphNodesNodeIdRoute
  '/api/nodes/$nodeId/impact': typeof ApiNodesNodeIdImpactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRoute
  '/api/agent-runs': typeof ApiAgentRunsRouteWithChildren
  '/api/agent-status': typeof ApiAgentStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/decisions/editorial': typeof ApiDecisionsEditorialRoute
  '/api/delivery/compile': typeof ApiDeliveryCompileRoute
  '/api/graph/nodes': typeof ApiGraphNodesRouteWithChildren
  '/api/provenance/$deliveryId': typeof ApiProvenanceDeliveryIdRoute
  '/api/runtime/proposals': typeof ApiRuntimeProposalsRoute
  '/api/script-git/apply': typeof ApiScriptGitApplyRoute
  '/api/script-git/load': typeof ApiScriptGitLoadRoute
  '/api/script-git/revert': typeof ApiScriptGitRevertRoute
  '/api/test/reset': typeof ApiTestResetRoute
  '/api/agent-runs/$runId/events': typeof ApiAgentRunsRunIdEventsRoute
  '/api/delivery/$variantId/approve': typeof ApiDeliveryVariantIdApproveRoute
  '/api/delivery/$variantId/resolve': typeof ApiDeliveryVariantIdResolveRoute
  '/api/graph/nodes/$nodeId': typeof ApiGraphNodesNodeIdRoute
  '/api/nodes/$nodeId/impact': typeof ApiNodesNodeIdImpactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace'
    | '/api/agent-runs'
    | '/api/agent-status'
    | '/api/health'
    | '/api/workspace'
    | '/api/decisions/editorial'
    | '/api/delivery/compile'
    | '/api/graph/nodes'
    | '/api/provenance/$deliveryId'
    | '/api/runtime/proposals'
    | '/api/script-git/apply'
    | '/api/script-git/load'
    | '/api/script-git/revert'
    | '/api/test/reset'
    | '/api/agent-runs/$runId/events'
    | '/api/delivery/$variantId/approve'
    | '/api/delivery/$variantId/resolve'
    | '/api/graph/nodes/$nodeId'
    | '/api/nodes/$nodeId/impact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workspace'
    | '/api/agent-runs'
    | '/api/agent-status'
    | '/api/health'
    | '/api/workspace'
    | '/api/decisions/editorial'
    | '/api/delivery/compile'
    | '/api/graph/nodes'
    | '/api/provenance/$deliveryId'
    | '/api/runtime/proposals'
    | '/api/script-git/apply'
    | '/api/script-git/load'
    | '/api/script-git/revert'
    | '/api/test/reset'
    | '/api/agent-runs/$runId/events'
    | '/api/delivery/$variantId/approve'
    | '/api/delivery/$variantId/resolve'
    | '/api/graph/nodes/$nodeId'
    | '/api/nodes/$nodeId/impact'
  id:
    | '__root__'
    | '/'
    | '/workspace'
    | '/api/agent-runs'
    | '/api/agent-status'
    | '/api/health'
    | '/api/workspace'
    | '/api/decisions/editorial'
    | '/api/delivery/compile'
    | '/api/graph/nodes'
    | '/api/provenance/$deliveryId'
    | '/api/runtime/proposals'
    | '/api/script-git/apply'
    | '/api/script-git/load'
    | '/api/script-git/revert'
    | '/api/test/reset'
    | '/api/agent-runs/$runId/events'
    | '/api/delivery/$variantId/approve'
    | '/api/delivery/$variantId/resolve'
    | '/api/graph/nodes/$nodeId'
    | '/api/nodes/$nodeId/impact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiAgentRunsRoute: typeof ApiAgentRunsRouteWithChildren
  ApiAgentStatusRoute: typeof ApiAgentStatusRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiWorkspaceRoute: typeof ApiWorkspaceRoute
  ApiDecisionsEditorialRoute: typeof ApiDecisionsEditorialRoute
  ApiDeliveryCompileRoute: typeof ApiDeliveryCompileRoute
  ApiGraphNodesRoute: typeof ApiGraphNodesRouteWithChildren
  ApiProvenanceDeliveryIdRoute: typeof ApiProvenanceDeliveryIdRoute
  ApiRuntimeProposalsRoute: typeof ApiRuntimeProposalsRoute
  ApiScriptGitApplyRoute: typeof ApiScriptGitApplyRoute
  ApiScriptGitLoadRoute: typeof ApiScriptGitLoadRoute
  ApiScriptGitRevertRoute: typeof ApiScriptGitRevertRoute
  ApiTestResetRoute: typeof ApiTestResetRoute
  ApiDeliveryVariantIdApproveRoute: typeof ApiDeliveryVariantIdApproveRoute
  ApiDeliveryVariantIdResolveRoute: typeof ApiDeliveryVariantIdResolveRoute
  ApiNodesNodeIdImpactRoute: typeof ApiNodesNodeIdImpactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-runs': {
      id: '/api/agent-runs'
      path: '/api/agent-runs'
      fullPath: '/api/agent-runs'
      preLoaderRoute: typeof ApiAgentRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-status': {
      id: '/api/agent-status'
      path: '/api/agent-status'
      fullPath: '/api/agent-status'
      preLoaderRoute: typeof ApiAgentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/decisions/editorial': {
      id: '/api/decisions/editorial'
      path: '/api/decisions/editorial'
      fullPath: '/api/decisions/editorial'
      preLoaderRoute: typeof ApiDecisionsEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delivery/compile': {
      id: '/api/delivery/compile'
      path: '/api/delivery/compile'
      fullPath: '/api/delivery/compile'
      preLoaderRoute: typeof ApiDeliveryCompileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph/nodes': {
      id: '/api/graph/nodes'
      path: '/api/graph/nodes'
      fullPath: '/api/graph/nodes'
      preLoaderRoute: typeof ApiGraphNodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provenance/$deliveryId': {
      id: '/api/provenance/$deliveryId'
      path: '/api/provenance/$deliveryId'
      fullPath: '/api/provenance/$deliveryId'
      preLoaderRoute: typeof ApiProvenanceDeliveryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/proposals': {
      id: '/api/runtime/proposals'
      path: '/api/runtime/proposals'
      fullPath: '/api/runtime/proposals'
      preLoaderRoute: typeof ApiRuntimeProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/script-git/apply': {
      id: '/api/script-git/apply'
      path: '/api/script-git/apply'
      fullPath: '/api/script-git/apply'
      preLoaderRoute: typeof ApiScriptGitApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/script-git/load': {
      id: '/api/script-git/load'
      path: '/api/script-git/load'
      fullPath: '/api/script-git/load'
      preLoaderRoute: typeof ApiScriptGitLoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/script-git/revert': {
      id: '/api/script-git/revert'
      path: '/api/script-git/revert'
      fullPath: '/api/script-git/revert'
      preLoaderRoute: typeof ApiScriptGitRevertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/reset': {
      id: '/api/test/reset'
      path: '/api/test/reset'
      fullPath: '/api/test/reset'
      preLoaderRoute: typeof ApiTestResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-runs/$runId/events': {
      id: '/api/agent-runs/$runId/events'
      path: '/$runId/events'
      fullPath: '/api/agent-runs/$runId/events'
      preLoaderRoute: typeof ApiAgentRunsRunIdEventsRouteImport
      parentRoute: typeof ApiAgentRunsRoute
    }
    '/api/delivery/$variantId/approve': {
      id: '/api/delivery/$variantId/approve'
      path: '/api/delivery/$variantId/approve'
      fullPath: '/api/delivery/$variantId/approve'
      preLoaderRoute: typeof ApiDeliveryVariantIdApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delivery/$variantId/resolve': {
      id: '/api/delivery/$variantId/resolve'
      path: '/api/delivery/$variantId/resolve'
      fullPath: '/api/delivery/$variantId/resolve'
      preLoaderRoute: typeof ApiDeliveryVariantIdResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph/nodes/$nodeId': {
      id: '/api/graph/nodes/$nodeId'
      path: '/$nodeId'
      fullPath: '/api/graph/nodes/$nodeId'
      preLoaderRoute: typeof ApiGraphNodesNodeIdRouteImport
      parentRoute: typeof ApiGraphNodesRoute
    }
    '/api/nodes/$nodeId/impact': {
      id: '/api/nodes/$nodeId/impact'
      path: '/api/nodes/$nodeId/impact'
      fullPath: '/api/nodes/$nodeId/impact'
      preLoaderRoute: typeof ApiNodesNodeIdImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiAgentRunsRouteChildren {
  ApiAgentRunsRunIdEventsRoute: typeof ApiAgentRunsRunIdEventsRoute
}

const ApiAgentRunsRouteChildren: ApiAgentRunsRouteChildren = {
  ApiAgentRunsRunIdEventsRoute: ApiAgentRunsRunIdEventsRoute,
}

const ApiAgentRunsRouteWithChildren = ApiAgentRunsRoute._addFileChildren(
  ApiAgentRunsRouteChildren,
)

interface ApiGraphNodesRouteChildren {
  ApiGraphNodesNodeIdRoute: typeof ApiGraphNodesNodeIdRoute
}

const ApiGraphNodesRouteChildren: ApiGraphNodesRouteChildren = {
  ApiGraphNodesNodeIdRoute: ApiGraphNodesNodeIdRoute,
}

const ApiGraphNodesRouteWithChildren = ApiGraphNodesRoute._addFileChildren(
  ApiGraphNodesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiAgentRunsRoute: ApiAgentRunsRouteWithChildren,
  ApiAgentStatusRoute: ApiAgentStatusRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiWorkspaceRoute: ApiWorkspaceRoute,
  ApiDecisionsEditorialRoute: ApiDecisionsEditorialRoute,
  ApiDeliveryCompileRoute: ApiDeliveryCompileRoute,
  ApiGraphNodesRoute: ApiGraphNodesRouteWithChildren,
  ApiProvenanceDeliveryIdRoute: ApiProvenanceDeliveryIdRoute,
  ApiRuntimeProposalsRoute: ApiRuntimeProposalsRoute,
  ApiScriptGitApplyRoute: ApiScriptGitApplyRoute,
  ApiScriptGitLoadRoute: ApiScriptGitLoadRoute,
  ApiScriptGitRevertRoute: ApiScriptGitRevertRoute,
  ApiTestResetRoute: ApiTestResetRoute,
  ApiDeliveryVariantIdApproveRoute: ApiDeliveryVariantIdApproveRoute,
  ApiDeliveryVariantIdResolveRoute: ApiDeliveryVariantIdResolveRoute,
  ApiNodesNodeIdImpactRoute: ApiNodesNodeIdImpactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
